spring.application.name=curso
server.port=8081

# Base de datos propia del MS cursos (apunta al contenedor mysql-db)
spring.datasource.url=jdbc:mysql://mysql-db:3306/curso?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.web-application-type=servlet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka (apunta al contenedor eureka-server)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true