# =========================================================
# rabbitmq.conf - Configuración del Cluster RabbitMQ
# Plataforma LC Digital CN
# =========================================================

# Clustering automático por peer discovery clásico
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-2

# Tiempo de espera entre intentos de descubrimiento (ms)
cluster_formation.node_cleanup.interval = 10000

# Política de ubicación de queue master: todos los nodos replican
queue_master_location = all
