FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -f plataforma_lc/pom.xml -pl :adminServer -am -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/plataforma_lc/sistema_infra/adminSpringBoot/target/*.jar app.jar
EXPOSE 8062
ENTRYPOINT ["java", "-jar", "app.jar"]