spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.renewal-percent-threshold=0.85
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=2000

logging.level.com.tupackage.eurekaserver.listeners=ERROR
logging.file.name=logs/eureka.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n

#eureka.server.enable-self-preservation=false
#eureka.server.eviction-interval-timer-in-ms=5000