spring.application.name=asistencia
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/asistencia
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.web-application-type=servlet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
# Reducir el tiempo de actualización de la caché de Eureka en el cliente
eureka.client.registry-fetch-interval-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=5
# Si Eureka no recibe un latido en 10 segundos, asume que el microservicio murió y limpia la ruta
eureka.instance.lease-expiration-duration-in-seconds=10
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true

#CircuitBreaker
#Integra el estado del circuito con Spring Boot Actuator.
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

#Resilience4j mirará el resultado de las últimas 10 llamadas para decidir si debe abrir o cerrar el circuito.
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
#Establece el número mínimo de llamadas necesarias para empezar a calcular errores.
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
#Define cuántas llamadas de "prueba" se permiten cuando el circuito está en estado Medio Abierto.
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
#Activa el paso automático del estado Abierto al Medio Abierto
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
#Es el tiempo que el circuito se queda "abierto" (bloqueando todo el tráfico).
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
#Es el umbral de error en porcentaje.
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
#Define el tamaño del buffer interno para los eventos del circuito (como cambios de estado).
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10

resilience4j.circuitbreaker.instances.estudianteService.base-config=default
resilience4j.circuitbreaker.instances.cursoService.base-config=default