spring.application.name=estudiante

spring.datasource.url=jdbc:mysql://localhost:3306/estudiante?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.web-application-type=servlet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


#CircuitBreaker
#Integra el estado del circuito con Spring Boot Actuator.
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

#Resilience4j mirará el resultado de las últimas 10 llamadas para decidir si debe abrir o cerrar el circuito.
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
#Establece el número mínimo de llamadas necesarias para empezar a calcular errores.
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
#Define cuántas llamadas de "prueba" se permiten cuando el circuito está en estado Medio Abierto.
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
#Activa el paso automático del estado Abierto al Medio Abierto
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
#Es el tiempo que el circuito se queda "abierto" (bloqueando todo el tráfico).
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
#Es el umbral de error en porcentaje.
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
#Define el tamaño del buffer interno para los eventos del circuito (como cambios de estado).
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10

resilience4j.circuitbreaker.instances.estudianteService.base-config=default

ms.curso.url=http://localhost:8081