spring.application.name=apiGateway
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=estudiante
spring.cloud.gateway.routes[0].uri=lb://estudiante
spring.cloud.gateway.routes[0].predicates[0]=Path=/estudiante/**

spring.cloud.gateway.routes[1].id=curso
spring.cloud.gateway.routes[1].uri=lb://curso
spring.cloud.gateway.routes[1].predicates[0]=Path=/curso/**

spring.cloud.gateway.routes[2].id=asistencia
spring.cloud.gateway.routes[2].uri=lb://asistencia
spring.cloud.gateway.routes[2].predicates[0]=Path=/asistencia/**
