spring.application.name=evaluaciones
server.port=8083

# Base de datos (apunta al contenedor mysql-db)
spring.datasource.url=jdbc:mysql://mysql-db:3306/evaluaciones?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.web-application-type=servlet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Eureka (apunta al contenedor eureka-server)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# Comunicación entre servicios (apunta a los nombres de contenedor en Docker)
ms.curso.url=http://curso:8081
ms.estudiante.url=http://estudiante:8080